name: Release Build
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Git Clone
        uses: actions/checkout@v4

      - name: Build for Releases
        run: |
          docker run --rm -t \
          -v $(pwd):/mnt -w /mnt \
          -e TAG="${GITHUB_REF#refs/tags/}" \
          rust bash ./release-build.sh
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            coomer-win-amd64.exe